-- Safety: set a timezone you expect to use in India
ALTER ACCOUNT SET TIMEZONE = 'Asia/Kolkata';

-- 1) Roles
CREATE ROLE IF NOT EXISTS AGRI_HELP_ADMIN;
CREATE ROLE IF NOT EXISTS AGRI_HELP_DEV;
CREATE ROLE IF NOT EXISTS AGRI_HELP_READONLY;

GRANT ROLE AGRI_HELP_DEV      TO ROLE AGRI_HELP_ADMIN;
GRANT ROLE AGRI_HELP_READONLY TO ROLE AGRI_HELP_ADMIN;

-- (Optional) grant to your user:
-- GRANT ROLE AGRI_HELP_ADMIN TO USER <YOUR_SNOWFLAKE_USER>;

-- 2) Warehouse
CREATE WAREHOUSE IF NOT EXISTS AGRI_HELP_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE, OPERATE ON WAREHOUSE AGRI_HELP_WH TO ROLE AGRI_HELP_ADMIN;
GRANT USAGE        ON WAREHOUSE AGRI_HELP_WH TO ROLE AGRI_HELP_DEV;
GRANT USAGE        ON WAREHOUSE AGRI_HELP_WH TO ROLE AGRI_HELP_READONLY;

-- 3) Database + Schemas
CREATE DATABASE IF NOT EXISTS AGRI_HELP COMMENT='AGRI_HELP app data';
GRANT OWNERSHIP ON DATABASE AGRI_HELP TO ROLE AGRI_HELP_ADMIN REVOKE CURRENT GRANTS;

USE ROLE AGRI_HELP_ADMIN;
USE WAREHOUSE AGRI_HELP_WH;
USE DATABASE AGRI_HELP;

CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS AGRONOMY;
CREATE SCHEMA IF NOT EXISTS IOT;
CREATE SCHEMA IF NOT EXISTS MARKET;
CREATE SCHEMA IF NOT EXISTS USERDATA;
CREATE SCHEMA IF NOT EXISTS WEATHER;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- Grants (tighten to your needs)
GRANT USAGE ON DATABASE AGRI_HELP TO ROLE AGRI_HELP_DEV, ROLE AGRI_HELP_READONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AGRI_HELP TO ROLE AGRI_HELP_DEV, ROLE AGRI_HELP_READONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AGRI_HELP TO ROLE AGRI_HELP_DEV, ROLE AGRI_HELP_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AGRI_HELP.ANALYTICS TO ROLE AGRI_HELP_READONLY;

-- 4) File formats (CSV & JSON commonly used for S3 ingestion)
CREATE OR REPLACE FILE FORMAT STAGING.CSV_STD
  TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 NULL_IF=('','NULL');

CREATE OR REPLACE FILE FORMAT STAGING.JSON_STD
  TYPE = JSON STRIP_OUTER_ARRAY = TRUE;

-- 5) (Recommended) Storage Integration for AWS S3 (replace placeholders)
-- Ask your Snowflake admin to create a STORAGE INTEGRATION once and wire to your S3 bucket
-- Docs: create the integration with your external_id in AWS IAM trust
CREATE OR REPLACE STORAGE INTEGRATION AGRI_HELP_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_FOR_SNOWFLAKE>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://your-bucket/agri-help/')
  COMMENT = 'S3 integration for AGRI_HELP';

DESC INTEGRATION AGRI_HELP_S3_INT;

-- 6) External stages (raw landing)
CREATE OR REPLACE STAGE STAGING.S3_RAW
  STORAGE_INTEGRATION = AGRI_HELP_S3_INT
  URL = 's3://your-bucket/agri-help/raw/'
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = STAGING.CSV_STD;

CREATE OR REPLACE STAGE STAGING.S3_JSON
  STORAGE_INTEGRATION = AGRI_HELP_S3_INT
  URL = 's3://your-bucket/agri-help/json/'
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = STAGING.JSON_STD;

-- 7) Governance: PII tag + basic masking policy
CREATE OR REPLACE TAG ANALYTICS.PII_TAG ALLOWED_VALUES ('PII','NON_PII');
CREATE OR REPLACE MASKING POLICY ANALYTICS.MASK_PHONE AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('AGRI_HELP_ADMIN','AGRI_HELP_DEV') THEN val
    ELSE REGEXP_REPLACE(val, '(\\d{2})\\d{6}(\\d{2})', '\\1******\\2')
  END;

-- =======================
-- CORE ENTITIES
-- =======================

-- Farmers & Farms
CREATE OR REPLACE TABLE CORE.FARMER (
  FARMER_ID         STRING PRIMARY KEY,
  FULL_NAME         STRING,
  PHONE             STRING TAG ANALYTICS.PII_TAG='PII',
  WHATSAPP          STRING,
  LANG              STRING DEFAULT 'en',
  TZ                STRING DEFAULT 'Asia/Kolkata',
  ADDRESS_LINE1     STRING,
  VILLAGE           STRING,
  DISTRICT          STRING,
  STATE             STRING,
  PINCODE           STRING,
  LAT               NUMBER(9,6),
  LON               NUMBER(9,6),
  LANDHOLDING_HA    NUMBER(10,2),
  CREATED_AT        TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT        TIMESTAMP_TZ
);

ALTER TABLE CORE.FARMER MODIFY COLUMN PHONE  SET MASKING POLICY ANALYTICS.MASK_PHONE;
ALTER TABLE CORE.FARMER MODIFY COLUMN WHATSAPP SET MASKING POLICY ANALYTICS.MASK_PHONE;

CREATE OR REPLACE TABLE CORE.FARM (
  FARM_ID           STRING PRIMARY KEY,
  FARMER_ID         STRING REFERENCES CORE.FARMER(FARMER_ID),
  FARM_NAME         STRING,
  AREA_HA           NUMBER(10,2),
  SOIL_TYPE         STRING,
  IRRIGATION_TYPE   STRING,      -- e.g., drip, flood
  LAT               NUMBER(9,6),
  LON               NUMBER(9,6),
  CREATED_AT        TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- =======================
-- AGRONOMY
-- =======================
CREATE OR REPLACE TABLE AGRONOMY.CROP (
  CROP_ID           STRING PRIMARY KEY,
  CROP_NAME         STRING,
  VARIETY           STRING,
  SEASON            STRING,      -- Kharif/Rabi/Zaid
  DURATION_DAYS     NUMBER(5),
  NOTES             STRING
);

CREATE OR REPLACE TABLE AGRONOMY.CROP_PLAN (
  PLAN_ID           STRING PRIMARY KEY,
  FARM_ID           STRING REFERENCES CORE.FARM(FARM_ID),
  CROP_ID           STRING REFERENCES AGRONOMY.CROP(CROP_ID),
  SOWING_DATE       DATE,
  HARVEST_DATE      DATE,
  AREA_HA           NUMBER(10,2),
  TARGET_YIELD_T_HA NUMBER(10,2),
  STATUS            STRING DEFAULT 'ACTIVE'
);

CREATE OR REPLACE TABLE AGRONOMY.SOIL_TEST (
  TEST_ID           STRING PRIMARY KEY,
  FARM_ID           STRING REFERENCES CORE.FARM(FARM_ID),
  SAMPLE_DATE       DATE,
  PH                NUMBER(4,2),
  EC_DS_M           NUMBER(6,3),
  N_KG_HA           NUMBER(10,2),
  P_KG_HA           NUMBER(10,2),
  K_KG_HA           NUMBER(10,2),
  ORGANIC_CARBON_%  NUMBER(4,2),
  SULPHUR_PPM       NUMBER(10,2),
  MICRO_NUTRIENTS   VARIANT,     -- JSON for Fe/Zn/B etc.
  LAB_NAME          STRING
);

CREATE OR REPLACE TABLE AGRONOMY.PEST_INCIDENT (
  INCIDENT_ID       STRING PRIMARY KEY,
  FARM_ID           STRING REFERENCES CORE.FARM(FARM_ID),
  CROP_ID           STRING REFERENCES AGRONOMY.CROP(CROP_ID),
  EVENT_TS          TIMESTAMP_TZ,
  PEST_NAME         STRING,
  SEVERITY          STRING,   -- Low/Med/High
  SYMPTOMS          STRING,
  IMAGE_URLS        ARRAY,
  RECOMMENDED_TX    STRING,
  APPLIED_TX        STRING,
  FOLLOWUP_DATE     DATE
);

-- =======================
-- IOT / SENSOR
-- =======================
CREATE OR REPLACE TABLE IOT.SENSOR (
  SENSOR_ID         STRING PRIMARY KEY,
  FARM_ID           STRING REFERENCES CORE.FARM(FARM_ID),
  SENSOR_TYPE       STRING,  -- soil_moisture, temp, humidity, ph, rainfall, flowmeter
  MODEL             STRING,
  INSTALLED_AT      TIMESTAMP_TZ,
  META              VARIANT
);

CREATE OR REPLACE TABLE IOT.SENSOR_READING (
  READING_ID        STRING PRIMARY KEY,
  SENSOR_ID         STRING REFERENCES IOT.SENSOR(SENSOR_ID),
  READING_TS        TIMESTAMP_TZ,
  METRIC            STRING,   -- temperature_c, soil_moisture_pct, etc.
  VALUE_NUM         FLOAT,
  UNIT              STRING
)
CLUSTER BY (SENSOR_ID, READING_TS);

-- =======================
-- WEATHER
-- =======================
CREATE OR REPLACE TABLE WEATHER.RAW_JSON (
  LOAD_TS           TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  FARM_ID           STRING,
  PROVIDER          STRING,
  PAYLOAD           VARIANT
);

CREATE OR REPLACE TABLE WEATHER.DAILY (
  DATE              DATE,
  FARM_ID           STRING,
  TMIN_C            NUMBER(5,2),
  TMAX_C            NUMBER(5,2),
  RAIN_MM           NUMBER(7,2),
  HUMIDITY_AVG_PCT  NUMBER(5,2),
  WIND_KMPH         NUMBER(6,2),
  SOURCE            STRING,
  PRIMARY KEY (DATE, FARM_ID)
);

-- =======================
-- MARKET / PRICES
-- =======================
CREATE OR REPLACE TABLE MARKET.MANDI_PRICE (
  PRICE_ID          STRING PRIMARY KEY,
  COMMODITY         STRING,
  MARKET_NAME       STRING,        -- e.g., 'Nashik'
  STATE             STRING,
  PRICE_DATE        DATE,
  MIN_PRICE         NUMBER(12,2),
  MAX_PRICE         NUMBER(12,2),
  MODAL_PRICE       NUMBER(12,2),
  UNIT              STRING,        -- Rs/quintal
  SOURCE            STRING
);

-- =======================
-- USERS / CHAT (Streamlit + LLM)
-- =======================
CREATE OR REPLACE TABLE USERDATA.APP_USER (
  USER_ID           STRING PRIMARY KEY,
  FARMER_ID         STRING REFERENCES CORE.FARMER(FARMER_ID),
  EMAIL             STRING,
  PHONE             STRING TAG ANALYTICS.PII_TAG='PII',
  ROLE              STRING DEFAULT 'farmer',
  LANG              STRING DEFAULT 'en',
  TZ                STRING DEFAULT 'Asia/Kolkata',
  CREATED_AT        TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
ALTER TABLE USERDATA.APP_USER MODIFY COLUMN PHONE SET MASKING POLICY ANALYTICS.MASK_PHONE;

CREATE OR REPLACE TABLE USERDATA.CHAT_SESSION (
  SESSION_ID        STRING PRIMARY KEY,
  USER_ID           STRING REFERENCES USERDATA.APP_USER(USER_ID),
  STARTED_AT        TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_ACTIVITY_AT  TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE USERDATA.CHAT_MESSAGE (
  MSG_ID            STRING PRIMARY KEY,
  SESSION_ID        STRING REFERENCES USERDATA.CHAT_SESSION(SESSION_ID),
  SENT_AT           TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  SENDER            STRING,            -- user/assistant
  TEXT              STRING,
  INTENT            STRING,
  MODEL             STRING,
  META              VARIANT
);

-- =======================
-- STAGING (raw landings for merges)
-- =======================
CREATE OR REPLACE TABLE STAGING.FARMER_CSV_LANDING (
  FULL_NAME         STRING,
  PHONE             STRING,
  LANG              STRING,
  ADDRESS_LINE1     STRING,
  VILLAGE           STRING,
  DISTRICT          STRING,
  STATE             STRING,
  PINCODE           STRING,
  LAT               NUMBER(9,6),
  LON               NUMBER(9,6),
  LANDHOLDING_HA    NUMBER(10,2)
);

-- Copy example from S3 into staging (CSV)
-- COPY INTO STAGING.FARMER_CSV_LANDING
--   FROM @STAGING.S3_RAW/farmers/
--   FILE_FORMAT = (FORMAT_NAME=STAGING.CSV_STD)
--   ON_ERROR='CONTINUE';

-- Upsert from staging to core
CREATE OR REPLACE PROCEDURE STAGING.MERGE_FARMERS()
RETURNS STRING
LANGUAGE SQL
AS
$$
INSERT INTO CORE.FARMER (
  FARMER_ID, FULL_NAME, PHONE, LANG, ADDRESS_LINE1, VILLAGE, DISTRICT, STATE, PINCODE, LAT, LON, LANDHOLDING_HA, CREATED_AT
)
SELECT
  COALESCE(HASH(FULL_NAME||PHONE||NVL(PINCODE,''))::STRING, UUID_STRING()),
  FULL_NAME, PHONE, LANG, ADDRESS_LINE1, VILLAGE, DISTRICT, STATE, PINCODE, LAT, LON, LANDHOLDING_HA, CURRENT_TIMESTAMP()
FROM STAGING.FARMER_CSV_LANDING;
$$;

-- Optional: Streams & Tasks for incremental pipelines
CREATE OR REPLACE STREAM STAGING.FARMER_CSV_LANDING_STREAM ON TABLE STAGING.FARMER_CSV_LANDING APPEND_ONLY=TRUE;

CREATE OR REPLACE TASK STAGING.LOAD_FARMERS_TASK
  WAREHOUSE = AGRI_HELP_WH
  SCHEDULE = 'USING CRON 30 * * * * Asia/Kolkata'
AS
  CALL STAGING.MERGE_FARMERS();

-- Enable the task (manually toggle)
-- ALTER TASK STAGING.LOAD_FARMERS_TASK RESUME;

-- =======================
-- Analytics views
-- =======================
CREATE OR REPLACE VIEW ANALYTICS.FARMER_SUMMARY AS
SELECT
  f.FARMER_ID,
  f.FULL_NAME,
  f.STATE,
  COUNT(DISTINCT fa.FARM_ID) AS FARMS,
  COUNT(DISTINCT cp.PLAN_ID) AS ACTIVE_CROPS,
  MAX(cp.HARVEST_DATE)       AS NEXT_HARVEST,
  COUNT(DISTINCT pi.INCIDENT_ID) AS PEST_EVENTS_30D
FROM CORE.FARMER f
LEFT JOIN CORE.FARM fa             ON fa.FARMER_ID = f.FARMER_ID
LEFT JOIN AGRONOMY.CROP_PLAN cp    ON cp.FARM_ID = fa.FARM_ID AND cp.STATUS='ACTIVE'
LEFT JOIN AGRONOMY.PEST_INCIDENT pi ON pi.FARM_ID = fa.FARM_ID AND pi.EVENT_TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY 1,2,3;
